
# Datasource properties
spring:
    application.name: order-service
    output.ansi.enabled: always
    zipkin.base-url: http://localhost:9411
    sleuth.sampler.probability: 1.0

server.port: 8084

eureka.instance:
    prefer-ip-address: true
    hostname: localhost

# Eureka server address 
eureka:
    client:
        serviceUrl.defaultZone: http://localhost:8761/eureka 

#Kafka configuration
spring.kafka:
    bootstrap-servers: localhost:9092
    template.default-topic: notificationTopic
    consumer.group-id: notificationId
    consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer.value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


    