# Datasource properties
spring:
    application.name: order-service
    h2.console.enabled: true
    datasource: 
        url: jdbc:h2:file:./order-service/db
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa.database-platform: org.hibernate.dialect.H2Dialect
    jpa.hibernate.ddl-auto: update
    output.ansi.enabled: always

server.port: 8082

eureka.instance:
    prefer-ip-address: true
    hostname: localhost

# Eureka server address 
eureka:
    client:
        serviceUrl.defaultZone: http://localhost:8761/eureka 

# Actuator properties
management:
    health.circuitbreakers.enabled: true
    endpoints.web.exposure.include: '*'
    endpoint.health.show-details: always

# Resilience4J properties
resilience4j.circuitbreaker.instances.inventory:
    registerHealthIndicator: true
    event-consumer-buffer-size: 10
    slidingWindowType: COUNT_BASED
    slidingWindowSize: 5
    failureRateThreshold: 50
    waitDurationInOpenState: 5s
    permittedNumberOfCallsInHalfOpenState: 3
    automaticTransitionFromOpenToHalfOpenEnabled: true

# resilience4J timeout exception
resilience4j.timelimiter.instances.inventory.timeout-duration: 3s