eureka:
    instance.hostname: localhost
    client:
        register-with-eureka: false
        fetch-registry: false

spring.output.ansi.enabled: always
server.port: 8761

eureka.instance.hostname: localhost

# Tracing
spring:
    zipkin.base-url: http://localhost:9411
    sleuth.sampler.probability: 1.0