spring:
    application.name: product-service
    output.ansi.enabled : always
    data:
        mongodb:
            uri: mongodb+srv://shivua1945:fN6TcbSCBOFml4D4@microservice.mz6t4i7.mongodb.net/Microservice?retryWrites=true&w=majority
            database: Microservice
    zipkin.base-url: http://localhost:9411
    sleuth.sampler.probability: 1.0

eureka.instance:
    prefer-ip-address: true
    hostname: localhost

server.port: 8081

# Password : fN6TcbSCBOFml4D4
# Username : shivua1945

# Eureka server address 
eureka:
    client:
        serviceUrl.defaultZone: http://localhost:8761/eureka 

    