
spring:
    h2.console.enabled: true
    datasource: 
        url: jdbc:h2:file:./inventory-service-db/db
        driverClassName: org.h2.Driver
        username: sa
        password:
 
    jpa.database-platform: org.hibernate.dialect.H2Dialect
    jpa.hibernate.ddl-auto: update

    output.ansi.enabled: always

server.port: 8083
