# Spring Datasource config
spring:
    application.name: inventory-service
    h2.console.enabled: true
    datasource: 
        url: jdbc:h2:file:./inventory-service/db
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa.database-platform: org.hibernate.dialect.H2Dialect
    jpa.hibernate.ddl-auto: update
    output.ansi.enabled: always
    zipkin.base-url: http://localhost:9411
    sleuth.sampler.probability: 1.0

server.port: 8083
# This will enable OS to provide a random Non-busy port to the application
# server.port: 0

eureka.instance:
    prefer-ip-address: true
    hostname: localhost

# Eureka server address 
eureka:
    client:
        serviceUrl.defaultZone: http://localhost:8761/eureka 
